# Generated by Django 4.1.3 on 2022-12-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qs_code', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wifiqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wifiqrcode',
            name='wifi_ip',
            field=models.ManyToManyField(related_name='wifi_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='vcardqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vcardqrcode',
            name='vcard_ip',
            field=models.ManyToManyField(related_name='vcard_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='urlqrcode',
            name='location',
            field=models.ManyToManyField(related_name='ip_address', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='urlqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twitterqrcode',
            name='twitter_ip',
            field=models.ManyToManyField(related_name='twitter_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='twitterqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textqrcode',
            name='text_ip',
            field=models.ManyToManyField(related_name='text_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='textqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsqrcode',
            name='sms_ip',
            field=models.ManyToManyField(related_name='sms_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='smsqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailqrcode',
            name='email_ip',
            field=models.ManyToManyField(related_name='email_ip', to='qs_code.ipaddress'),
        ),
        migrations.AddField(
            model_name='emailqrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='email_qr',
            field=models.ManyToManyField(to='qs_code.emailqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sms_qr',
            field=models.ManyToManyField(to='qs_code.smsqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='text_qr',
            field=models.ManyToManyField(to='qs_code.textqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='twitter_qr',
            field=models.ManyToManyField(to='qs_code.twitterqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='url_qr',
            field=models.ManyToManyField(related_name='url_dashboard', to='qs_code.urlqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='vcard_qr',
            field=models.ManyToManyField(to='qs_code.vcardqrcode'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='wifi_qr',
            field=models.ManyToManyField(to='qs_code.wifiqrcode'),
        ),
    ]
